from myapp.ClassViews.index import index
from myapp.ClassViews.listing import Listing
from myapp.ClassViews.product_listing import product_listing
from myapp.ClassViews.add_items import additems
from myapp.ClassViews.signup import SendOTP,CheckOTP
from myapp.ClassViews.login import Login,logout
from myapp.ClassViews.checkout import Checkout,checkitems
from myapp.ClassViews.create_payment import CreatePayment,verfiyPayment,Summary
from myapp.ClassViews.forget_password import ForgetPassword,OTPVerification,PasswordVerification
